### ISSUE TITLE
Can't find the file and or url

### ISSUE THREAD

**Issue by Andynam0** [BoredHackerBlog/runcmd#1]
It's not running on win10/11

runcmd.exe -file cmd.txt (or -url https://abc.com/cmd.txt)

exec: "<?xml": executable file not found in %PATH%
exec: "<Error><Code>AccessDenied</Code><Message>Access": file does not exist

**Comment by BoredHackerBlog** [comment]
I think it might have to do with file contents?
Input from the file comes in as "<?xml" OR "AccessDenied Access"

**Comment by Andynam0** [comment]
doh! You're right! It's working ;p
